### ISSUE TITLE
AsyncAPI: Library for easier integration testing of code generators

### ISSUE THREAD

**Issue by AceTheCreator** [postman-open-technologies/gsoc-2024#6]
This project addresses the needs of template maintainers, particularly those overseeing code-generating templates. The goal is to develop a dedicated feature within the generator or potentially create a standalone library that can be effortlessly enabled in repositories. The envisioned capability allows maintainers to seamlessly activate integration tests specifically tailored to their code generation templates. By creating this testing library, template maintainers will benefit from a streamlined process to ensure the robustness and reliability of their templates, enhancing overall code generation quality and reliability.

Additionally, contributors will have the opportunity to code in JavaScript or TypeScript, collaborate on a solution that will be used across the AsyncAPI organization, delve into the intricacies of writing a testing library, and gain hands-on experience with Docker, virtualization, and testing automation.

Learn more here https://github.com/asyncapi/generator/issues/752

**Mentor/s**: 
@derberg

**Project Repo:** 
https://github.com/asyncapi/generator

**Expected Difficulty**:
Medium-Hard

**Expected Time Commitment**:
175 Hour

**Comment by fmvilas** [comment]
This year we need to learn if code generators (the way we're providing them right now) is something we want to invest in. Seems like a bad idea to me but I don't have the numbers yet. Maybe we can explore other ways to build code generators. Check with @jonaslagoni.

**Comment by jonaslagoni** [comment]
I concur but have nothing concrete yet to share, but it will probably be done as part of working groups once implemented https://github.com/orgs/asyncapi/discussions/1037#discussioncomment-8371604

**Comment by GaganMeshram123** [comment]
@derberg Hello! I'm Gagan Meshram, a Computer Science undergraduate from India with a passion for open-source contributions. Previously, I had the opportunity to participate in Google Summer of Code at Rocket.chat, which was an enriching experience. This season, I'm eager to channel my skills and knowledge into contributing to AsyncAPI. This project has captured my interest and I would love to build this VS code extension, and I'm excited about the potential impact I can make by contributing to AsyncAPI. I'm looking forward to contributing and making some impact...
